apiVersion: v1
kind: Pod
metadata:
  name: pod-multicontenedor
  labels:
    modulo: "01-pods"
spec:
  # Volumen compartido entre contenedores
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:
  # Contenedor principal - sirve web
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  # Sidecar - genera contenido cada 5 segundos
  - name: sidecar-writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "<h1>Hola desde sidecar! $(date)</h1>" > /data/index.html
        sleep 5
      done
    volumeMounts:
    - name: shared-data
      mountPath: /data
