apiVersion: v1
kind: Pod
metadata:
  name: pod-init-container
  labels:
    modulo: "01-pods"
spec:
  # InitContainers corren ANTES que los contenedores principales
  # Se usan para preparar el entorno (esperar BBDDs, copiar configs, etc.)
  initContainers:
  - name: init-esperar
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "Init: preparando entorno..."
      sleep 5
      echo "Init: entorno listo!"

  - name: init-crear-archivo
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - echo "Contenido generado por init" > /work/index.html
    volumeMounts:
    - name: work-dir
      mountPath: /work

  containers:
  - name: app
    image: nginx:alpine
    volumeMounts:
    - name: work-dir
      mountPath: /usr/share/nginx/html

  volumes:
  - name: work-dir
    emptyDir: {}
