datadog:
  site: "datadoghq.eu"
  clusterName: "minikube-fove"
  apiKeyExistingSecret: "datadog-secret"
  clusterChecks:
    enabled: true
  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  kubelet:
    tlsVerify: false
  # Deshabilita checks de componentes no accesibles en Minikube
  kubeScheduler:
    enabled: false
  kubeControllerManager:
    enabled: false
  etcd:
    enabled: false
providers:
  gke:
    gch:
      enabled: false
