apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-s3-deployment
  labels:
    app: mi-app-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-s3
  template:
    metadata:
      labels:
        app: mi-app-s3
      annotations:
        ad.datadoghq.com/python-app.logs: '[{"source":"python","service":"app-s3"}]'
    spec:
      containers:
      - name: python-app
        image: mi-app-s3:local
        imagePullPolicy: Never
        env:
        - name: LOCALSTACK_URL
          value: "http://192.168.49.1:4566"
        - name: BUCKET_NAME
          value: "terraform-localstack-bucket"
        - name: PYTHONUNBUFFERED
          value: "1"
