apiVersion: v2
name: mi-app-chart
description: Helm Chart para la app Python que interactúa con LocalStack S3
type: application
version: 0.2.0
appVersion: "2.0.0"
maintainers:
  - name: fovehack
    email: reactydev@gmail.com
