# Valores por defecto - se pueden sobreescribir al instalar

replicaCount: 1

image:
  repository: mi-app-s3
  tag: local
  pullPolicy: Never        # Never = usa imagen local de Minikube

localstack:
  url: "http://192.168.49.1:4566"
  bucketName: "terraform-localstack-bucket"

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

env:
  pythonUnbuffered: "1"

datadog:
  logsEnabled: true
  source: "python"
  service: "app-s3"
